name: ci

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Formatter
        run: |
          output=$(gofmt -l .)
          if [ -n "$output" ]; then
            echo "these files are not formatted:" >&2
            echo "$output" >&2
            exit 1
          fi
      - name: Build
        run: go build ./...
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./... -count=1
